#!/usr/bin/env bash
# Install and configure HAproxy and send traffic
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http_web
    bind *:80
    default_backend web-backend
backend web-backend
    balance roundrobin
    server 3363-web-01 34.138.29.20 check
    server 3363-web-02 34.74.165.238 check
EOT
sudo service haproxy start
