#!/usr/bin/env bash
# Install and configure HAproxy and send traffic
sudo apt -y install haproxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http_web
    bind *:80
    default_backend rgw
backend rgw
    balance roundrobin
    server  rgw1 34.138.29.20 check
    server  rgw2 34.74.165.238 check
EOT
sudo service haproxy restart
