#!/usr/bin/env bash
# Script that displays the time for 12 hours
hour=0
min=0
echo "Hour: $hour"
while :
do
		min=$(( min + 1 ))
		echo $min
        if [ "$min" -eq 99 ]
        then
			if [ "$hour" -eq 12 ]
			then
				hour=0
			else
				hour=$(( hour + 1 ))
			fi
			echo "Hour: $hour"
			min=0
        fi
        
done
